[workspace]
members = ["jupiter-core"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
anchor-lang = "0.28"
anchor-syn = "0.28"
solana-sdk = "~1.16"
solana-client = "~1.16"
solana-program-test = "~1.16"

anchor-gen = "0.3"
