[workspace]
members = ["symmetry-math"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
anchor-lang = "0.29"
anchor-syn = "0.29"
solana-sdk = "~1.18"
solana-client = "~1.18"
solana-program-test = "~1.18"

anchor-gen = "0.3"
